### ISSUE TITLE
Issue with the checker

### ISSUE THREAD

**Issue by FedericoAlonsoPecina** [rte-france/challenge-roadef-2020#12]
Hi!
I find a issue with the checker, I have the next solution for the instance A_09:

Intervention_257 14
Intervention_31 6
Intervention_652 10
Intervention_212 14
Intervention_580 14
Intervention_503 4
Intervention_552 2
Intervention_660 13
Intervention_309 9
Intervention_659 14
Intervention_680 15
Intervention_653 15
Intervention_259 8
Intervention_63 12
Intervention_345 13
Intervention_602 14
Intervention_90 1
Intervention_385 2

And the checker give me the next output:

Done
Loading solution from A_09_57.out...
Done
Checking constraints...
        Checking schedule constraints...
        Done
        Checking resources constraints...
ERROR: Resources constraint 4.2 upper bound: Worload on Resource Resources_control at time 15 exceeds upper bound. Value 1.71 is greater than bound 0.7941176471 plus tolerance 1e-05.
ERROR: Resources constraint 4.2 upper bound: Worload on Resource Resources_control at time 16 exceeds upper bound. Value 1.0 is greater than bound 0.7941176471 plus tolerance 1e-05.
        Done
        Checking exclusions constraints...
        Done
Done
Computing objectives values...
        Computing risk...
        Done
        Computing mean risk...
        Done
        Computing Quantile...
        Done
Done
Instance infos:
        Interventions number:  18
        Scenario numbers:  17
Solution evaluation:
        Objective 1 (mean risk):  3048.5019215686275
        Objective 2 (expected excess  (Q0.5)):  0.32564705882352785
        Total objective (alpha*mean_risk + (1-alpha)*expected_excess):  1524.4137843137255

But I check with and excel the days 15 and 16 and do not exceeds the upper bound,...

**Comment by klorel** [comment]
Hi!
Could you send us what you have computed in your excel file ? 
This ressource has bounds that change at that particular time time, moving from 1058.8235294118  to 0.794117647, may be it is a time shift issue?
Hope this help
Manuel

**Comment by wfb7** [comment]
Intervention_309 starts at time step 9 and has duration 9. This intervention requires 1.0 of resource "Resources_control" in time step 16 ("16":{"8":0.71,"9":1.0}) which is greater than the maximum allowed (0.794118).

**Comment by FedericoAlonsoPecina** [comment]
Thanks a lot!
