### ISSUE TITLE
Evaluation computer

### ISSUE THREAD

**Issue by wfb7** [rte-france/challenge-roadef-2020#17]
In the challenge rules it's stated: "The computer that should be used to evaluate programs of candidates is a Linux OS machine with 2 CPU, 16GB of RAM."

Could you please give more details on the machine?
 Is multi-threading allowed?

**Comment by klorel** [comment]
Hello, 
At the moment we cannot provide more details on the machine (every thing should be done in the cloud). Multithreading is alllowed (2CPU will be available).

**Comment by wfb7** [comment]
Hello,

Could we at least know the clock speed (GHz)? It's important information for many of the competing teams I guess.

**Comment by wfb7** [comment]
Any news on this?
Could we send our executable few days/weeks before the deadline so you can run it and give us the feedback?

**Comment by klorel** [comment]
Hello, 
Here are information regarding the testing environment:
Distribution : Debian 10 stable
CPU : Intel i7-6700K 4c / 8t 4GHz
RAM : 16GB

**Comment by wfb7** [comment]
Thanks!
