### ISSUE TITLE
Qualification round program requirements

### ISSUE THREAD

**Issue by psarka** [rte-france/challenge-roadef-2020#20]
Hello, I have two questions with regards to the program that we should submit for the qualification round.

1. Can it contain short instalation instructions? Such as 

```bash
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install .
```
2. Should the program bundle the problem files? Or can it contain instructions such as

> extract A_set.7z to the `data/` folder

Thanks!

**Comment by klorel** [comment]
Hello!
For 1- yes! Please just put this in a README file so that it an be easily identified.

For 2-, no, we will put the data on the computer so the executable will be called as specified in the rules document.

Good luck for the final stretch!

**Comment by psarka** [comment]
Thanks! Just a clarification for the 2. point: the website says:

> -p instance_name to load the data associated with the instance. 

Does this mean that you will pass a string such as `'A_01'`, and  the program will have to find the file itself (in which case it is still not clear where to look for it), or do you intend to pass the full path such as `'/some/location/A_01.json'`?

**Comment by klorel** [comment]
Hi again,
Thank you for your question, I think it will help all the competitors. We will give the full path of the file.
