### ISSUE TITLE
Can not register on the site

### ISSUE THREAD

**Issue by RedMoon32** [rte-france/challenge-roadef-2020#22]
Hello! I registered myself as a Junior team yesterday (Rinat Babichev BS 4 Innopolis University student, Russia) however, I still did not get any response in my mailbox
Can you please check?

**Comment by cybervalient** [comment]
Dear organizer, .Can You please confirm the new registers?Thanks and Best regards..

**Comment by RedMoon32** [comment]
@cybervalient are you still too not registered?

**Comment by cybervalient** [comment]
I not registered too!!
