### ISSUE TITLE
Semi-final phase

### ISSUE THREAD

**Issue by teamxSxoptimiz** [rte-france/challenge-roadef-2020#25]
The semi final phase will end on March 8 2021 and we will be competing on set B of instances. Are we allowed/requested to send a new version of the program before that deadline?

Thanks

**Comment by klorel** [comment]
Dear competitors,
Please refer to the dedicated web page : https://www.roadef.org/challenge/2020/en/calendrier.php
New contribution are to be sent before March 16th 2021.

**Comment by teamxSxoptimiz** [comment]
Great, thanks. What is the protocol for the submission? The same protocol used for the qualification phase but changing the subject to "ROADEF/EURO challenge 2020 semi final material from XX"?
