### ISSUE TITLE
Using open source solvers

### ISSUE THREAD

**Issue by mfacc** [rte-france/challenge-roadef-2020#26]
According to the rules we are allowed to implement our solvers relying on CPLEX, Gurobi and/or LocalSolver. Will we be allowed to use well known open source solvers such us GLPK, SCIP, CBC or Google's OR-Tools for the following phases?

Thanks!

**Comment by klorel** [comment]
Hello!
Yes for sure you will be able to use any open-source solver, as long as you provide how to build them on the evaluation environment.

**Comment by mfacc** [comment]
Thanks!
