### ISSUE TITLE
Instances B set available!

### ISSUE THREAD

**Issue by klorel** [rte-france/challenge-roadef-2020#27]
For those who haven't seen the update on the repository, B instances have been published, good luck!

**Comment by fontanf** [comment]
@klorel Is it possible to bound the number of decimals in resources? For example, in `B_05`, there are values like `0.028999999999999998` or `0.29700000000000004`  . This will cause numerical issues and I bet it does not matter for the real problem

**Comment by klorel** [comment]
@fontanf We totally agree ! This should be fixed quickly, I will keep you informed.

**Comment by klorel** [comment]
Cleaned instance B set is available :)
Please share with us any other feedback, it is very useful.
Good Luck !

**Comment by fontanf** [comment]
It looks perfect, thanks!

**Comment by wfb7** [comment]
What about the qualification results, are they coming soon? It's though to work on set B with no feedback on set A for more than a month.
