### ISSUE TITLE
please check A_01.json

### ISSUE THREAD

**Issue by christos-tsotskas** [rte-france/challenge-roadef-2020#6]
When running some tests, model for risk calculation of Intervention_77 on A_01.json was failing because of lack of data. Interestingly, the provided checker did not pick this up.....

```
    for i, additional_risk in enumerate(intervention_risk[time_plus_one][start_time]):
KeyError: '61'

```

according to the provided files
```
Intervention_77
start_time= 61
{
  "29": [
    1019.65
  ],
  "30": [
    1019.65
  ],
  "31": [
    1019.65
  ],
  "32": [
    1019.65
  ],
  "33": [
    1019.65
  ],
  "34": [
    1019.65
  ],
  "35": [
    1019.65
  ],
  "36": [
    1019.65
  ],
  "37": [
    1019.65
  ],
  "38": [
    1019.65
  ],
  "39": [
    1019.65
  ],
  "40": [
    1019.65
  ],
  "41": [
    1019.65
  ],
  "42": [
    1019.65
  ],
  "43": [
    1019.65
  ],
  "44": [
    1019.65
  ],
  "45": [
    1019.65
  ],
  "46": [
    1019.65
  ],
  "47": [
    1019.65
  ],
  "48": [
    1019.65
  ],
  "49": [
    1019.65
  ],
  "50": [
    1019.65
  ],
  "51": [
    1019.65
  ],
  "52": [
    1019.65
  ],
  "53": [
    1019.65
  ],
  "54": [
    1019.65
  ],
  "55": [
    1019.65
  ],
  "56": [
    1019.65
  ],
  "57": [
    1019.65
  ],
  "58": [
    1019.65
  ]
}

```

which proves the error stated above

It just happened and I used A_01.json, for A_03.json I did not notice anything.
Please update A_set or advise accordingly.

Happy to provide any feedback, as required.

Many Thanks,
Christos

**Comment by klorel** [comment]
Hi Christos,
Could you send us the solution file producing the issue ? It will help us to understand.
Thanks for the feedback.
Manuel

**Comment by christos-tsotskas** [comment]
yes, sure, which e-mail address shall I use? (feel free to reply to my e-mail address I provided when registered)

**Comment by klorel** [comment]
I think you can drag and drop the file in the issue comment box.
Manuel
