### ISSUE TITLE
Clarification of the risk values

### ISSUE THREAD

**Issue by itlchriss** [rte-france/challenge-roadef-2020#7]
How do we interpret the number of risk values?

Such as in A_02.json, we have risks in intervention with 6 values and 5 values. And in some other tasks with 4 values.  Although we know the length of risk should be equal to the length of scenario_number, but both the index of the inner array and the number of values in the inner array are confusing. Would you mind providing explanation on this?

Thanks and Best Regards

Chriss IT. L.

**Comment by klorel** [comment]
Hi Chriss,
Risk values were computed using an homemade grid simulator. They capture the risk increasment at t because an intervention has started at t'.  
The length of the risk ditribution is equal to the number of scenarios that were used by the simulator, so it is not necessarily the same.
Hope this help.
Manuel

**Comment by itlchriss** [comment]
Hi Manuel,

   Thanks for the prompt reply. 
   I want to have a better understanding in the computation. For the multiple number of risk value in a certain starting time 't' in an intervention, let me take A_02.json -> Intervention_108 as an example. We have,
   risk: { 1: { 1: [...], 2: [...]....}
   What should we consider the first "1" and the second "1"?
   Furthermore, are we taking the mean of the values in the "[]" as a mean risk value in computing the objective?

Thanks and Best Regards

Chriss IT. L.

**Comment by klorel** [comment]
For understanding the format please see https://github.com/rte-france/challenge-roadef-2020/blob/master/README.md#risk
For understanding the computation, both the subject and the rules document describe what we do.
Manuel

**Comment by itlchriss** [comment]
Hi Manuel,

I have read the README. What my question is as the following,
"Risk
"t": {"st_1":[...], "st_2":[...]}

Risk values for each scnerio are given for each timestep "t", and depending on the intervention starting time "st".
For a given "t" and "st", risk is a list whose size is equal to the number of scenario (see below) for the current timestep. It gives a risk value for each of the scenario.

"risk": {
  "1": {"1": [4, 8, 2], "2": [0, 0, 0]},
  "2": {"1": [0, 0], "2": [3, 8]},
  "3": {"1": [0, 0, 0], "2": [0, 0, 0]}
sss}"

As stated above, "It gives a risk value for each of the scenario.", but there are three values or two values as an array. Are we considering the "a risk value" to be a mean of such as "4, 8, 2"?

**Comment by klorel** [comment]
The number of scenarios may be different depending on the timestep.

To compute the average risk at a time t, sum all the risk values for interventions occuring at t, this will give you the risk distribution of the planning at t. The mean of the distribution is used to compute the average risk value. But note the the distribution is also used to compute the excess.
Hope this is clear and useful for everybody.
Manuel

**Comment by itlchriss** [comment]
Thank you very much for the explanation.

> The number of scenarios may be different depending on the timestep.
> 
> To compute the average risk at a time t, sum all the risk values for interventions occuring at t, this will give you the risk distribution of the planning at t. The mean of the distribution is used to compute the average risk value. But note the the distribution is also used to compute the excess.
> Hope this is clear and useful for everybody.
> Manuel
