### ISSUE TITLE
Resources min and max

### ISSUE THREAD

**Issue by itlchriss** [rte-france/challenge-roadef-2020#9]
In the Rules document, I found the statement : "In "Resources", "min" and "max" are ordered lists of length T". 
Can we consider an intervention starting at different time with resources will have different max and min stated in the list?

**Comment by klorel** [comment]
Hi!
Sorry I'm not sure I understand the question. There is Min and Max values for each ressources and each time.
Interventions require ressource worload load, but they don't have min/max on ressources.
Could you clarify your question ? 
Thank you in advance
Manuel

**Comment by itlchriss** [comment]
Hello Manuel,
such as in A_07.json, we have Ressources_9 with min and max, both have length of T.  As I notice, the last six values in max are different with others in the max of Ressources_9. 
My question is, are we using different min and max as constraint with reference to the intervention starting time?
Such as, if an intervention uses Ressources_9 with starting time is 1, we use min = 0 and max = 1.0. If another intervention uses the same resource with starting time is 12, we use min = 0 and max = 1.7?

Thanks and Best Regards
Chriss

**Comment by itlchriss** [comment]
Hello Manuel,
please let me add another question here about the resources and interventions.
Imagine there is an instance with T = 10, I1 and I2 has delta of 5 and both uses 2 units of R1 at T = 2. R1 has a declaration of max = { 2: { 2: 5 }, 3: { 3: 5}}
If we have scheduled both I1 and I2 with T = 2. Then we want to schedule I3 which uses also 2 units of R1 at T = 3. In this case, as I1 and I2 still move on when T = 3, do we have to account the consumption of I1 and I2 in scheduling I3? aka, is the resource still occupied within the time phrase of starting time + delta ?

Thanks and Best Regards
Chriss

**Comment by klorel** [comment]
The starting time is only used to have to ressource consumption of an intervention at a time t (depending on when the intervention started).  

With that, you are able to compute the ressource used at each time t by the sum over intervention worload (which  again, depends on the starting time). The min/max to apply is then the one related to t.

Hope this help
Manuel

**Comment by klorel** [comment]
Hi Chriss, 
Our posts crossed each other. 
A comment: the declaration of max is strange, there should be only one value for each time. 

Please refer to the section 3.3 of the challenge rules document, there is a small example illustrating the time discretization. The ressource should not be taken into account for time step starting time + delta.

Hope this help
Manuel

**Comment by itlchriss** [comment]
Hi Manuel,
Thanks for the clarifications!
I want to follow up with the workload declarations in the interventions. 
As I saw, in A_07.json we have a workload in intervention_376 as the following,
            "workload":{
                "Ressources_2":{
                    "1":{
                        "1":0.86
                    },
                    "2":{
                        "1":0.57,
                        "2":1.0
                    },
                    "3":{
                        "2":0.43,
                        "3":1.0
                    },
                    "4":{
                        "3":0.43,
                        "4":1.0
                    },
                    "5":{
                        "4":0.43,
                        "5":1.0
                    },
                    "6":{
                        "5":0.43,
                        "6":1.0
                    },
                    "7":{
                        "6":0.43,
                        "7":1.0
                    },
                    "8":{
                        "7":0.43,
                        "8":1.0
                    },
                    "9":{
                        "8":0.43,
                        "9":1.0
                    },
                    "10":{
                        "9":0.43,
                        "10":1.0
                    },
                    "11":{
                        "10":0.43,
                        "11":1.0
                    },
                    "12":{
                        "11":0.43,
                        "12":1.0
                    },
                    "13":{
                        "12":0.43,
                        "13":1.0
                    },
                    "14":{
                        "13":0.43,
                        "14":1.0
                    },
                    "15":{
                        "14":0.43,
                        "15":1.0
                    },
                    "16":{
                        "15":0.43,
                        "16":1.0
                    },
                    "17":{
                        "16":0.43
                    }
                },

For the intervention_376, each delta is two. 
For example if the starting time is 16, we are looking at                    
 "16":{
                        "15":0.43,
                        "16":1.0
                    },. How should we interpret the 15 and 16? 
I don't get why there is a number inside that is smaller than the outside starting time key.

Thanks and Best Regards

Chriss
